= map openapi array (globally) to a java collection type

By default the OpenAPI `array` is mapped to a simple java array. That is probably the first thing
you want to change.

To change that default mapping for example to `java.util.Collection` a simple global type mapping
is required in the xref:mapping/index.adoc[`mapping.yaml`].

Given the following openapi.yaml fragment:

[source,yaml]
----
paths:

  /array:
    get:
      responses:
        '200':
          description:
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
----

the processor will create the following endpoint interface using the default array mapping:

[source,java]
----
@GetMapping(path = "/array", produces = {"application/json"});
ResponseEntity<String[]> getArray();
----

To globally change the mapping of `array` to another collection type we just need to add a simple
*global* type mapping to the xref:mapping/index.adoc[`mapping.yaml`]:

[source,yaml]
----
map:
  types:
    # map array to java.util.Collection
    - from: array
      to: java.util.Collection
----

This will change the generated endpoint to:

[source,java]
----
@GetMapping(path = "/array", produces = {"application/json"});
ResponseEntity<Collection<String>> getArray();
----

[IMPORTANT]
====
the processor assumes that the given java type has a single generic parameter and will automatically
use the ``array``'s `item` property type as the generic parameter.
====
