= Configuration
include::partial$links.adoc[]

The configuration of the processor is read from the (mandatory) `mapping.yaml` file. It does contain
some  general options and the xref:mapping/index.adoc[mapping] type information.

A mapping yaml looks like this

[source,yaml]
----
options:
  package-name: com.github.hauner.openapi
  bean-validation: true

map:
   # java type mappings
----


== options:

* `package-name`: (**required**) the root package name of the generated interfaces & models. The
package  folder tree will be created inside the `targetDir` (see xref:gradle.adoc[using gradle]).
+
Interfaces and models will be generated into the `api` and `model` subpackages of `package-name`.
+
** so the final package name of the generated interfaces will be `"$\{package-name\}.api"`
** and the final package name of the generated models will be `"$\{package-name\}.model"`

* `bean-validation` (**optional**, `true` or `false`) enables generation of bean validation
annotations. Defaults to `false`. See link:{bean-validation}[Bean Validation, window="_blank"].

== map:

Using type mapping we can tell the processor to map types (schemas) from an `openapi.yaml`
description to a specific existing java type instead of generating a model class from the source
OpenAPI type.

This is one of the core features and has his own description in xref:mapping/index.adoc[mapping].
