= Responses

:spring-responseentity: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/ResponseEntity.html


All generated endpoints return their java result type by default. This may be to simple for some
endpoint implementations.

There are two mappings available to customize the result type:

. If for example the response needs some customization we would like to use a `ResponseEntity<>`
to modify it. This is possible using the *result* mapping.

. Another case is WebFlux, where we need the result to be either a `Flux<>` in case of an array
type, or a `Mono<>` in case it is not an array type. This is possible using the *single* mapping.


NOTE: *single* & *result* mappings are _independent_, i.e. both mappings can be used at the same
time. For example, it is possible to create a `Mono<>` result and modify the response using
`ResponseEntity<>`. The response type would be `ResponseEntity<Mono<...>>`.


== result wrapper

[.badge .badge-since]+since 1.0.0.M13+


A link:{spring-responseentity}[`ResponseEntity<>`] allows an endpoint implementation full control of
the response.

Here is a super simple examples:

[source,java]
----
public ResponseEntity<String> getFoo() {
    return ResponseEntity.ok("foo");
}
----

To enable a result wrapper set the `result` mapping in the mapping yaml to a fully qualified java
type.

[source,yaml]
----
map:
  result:
    to: org.springframework.http.ResponseEntity
----

NOTE: The processor expects that it takes a single generic parameter.

Depending on the number of defined response content types the parameter of the `ResponseEntity<>`
will be either the java type or the *unknown type*.

|===
|responses | ResponseEntity<>

|one
|`ResponseEntity<java type>`

|multiple
|`ResponseEntity<?>`
|===

NOTE: prior to 1.0.0.M13 all results were auto-wrapped with `ResponseEntity<>`.

== single wrapper

[.badge .badge-since]+since 1.0.0.M13+

When using WebFlux we want to wrap the result types in a reactive type. For array like types we can
simply use the standard `array` mapping:

[source,yaml]
----
map:
  types:
    - from: array
      to: reactor.core.publisher.Flux
----

Which will use `Flux<>` as collection wrapper instead of an java array for all list parameters
or responses.

To map non-array like responses to a `Mono<>` set the `single` mapping:

[source,yaml]
----
map:
  single:
    to: reactor.core.publisher.Mono
----

The processor will now wrap all non-array like response types with the given `single` mapping.
