= Type mapping

Type mapping is an important feature of the processor and helps it to create the expected code.

Using type mapping we can tell the processor to map types (schemas) from an openapi.yaml description
to a specific existing java type instead of generating a model class from the source OpenAPI type.

This can be a type created by us or a type from a framework. For example to map paging parameters
and result to the Spring types `Page<>` & `Pageable`.

It can also be used to map the OpenAPI `array` type to a different java collection type if the
default does not fulfill our needs.

Type mapping is very flexible. It is possible to define the mapping globally, globally for a
specific response or parameter or even limited to a specific endpoint.

Type mapping also supports generic parameters to the target type. One level. That means you can
provide generic types for the direct target type but not for nested types of the target.

Type mapping works best with named schemas (i.e. schemas `$ref`erenced by their name).
