package com.github.hauner.openapi.spring.writer

class HeaderWriter {

    static String HEADER = """\
/**
 * This class is auto generated by https://github.com/hauner/openapi-spring-generator.
 * DO NOT EDIT.
 */
"""

    void write(Writer target) {
        target.write (HEADER)
    }
}
