include::partial$links.adoc[]

= Gradle Plugin

The xref:gradle::index.adoc[openapi-processor-gradle] Gradle plugin can run any of the **openapi-processor**'s.

To use it in a Gradle project, the Gradle file of the project requires a few additional instructions. The following sections describe how to activate and configure **openapi-processor-spring** in a `build.gradle` file.


== adding the plugin

To activate the plugin, add it to (like any other Gradle plugin) the `plugins` configuration:

[source,groovy]
----
plugins {
    ....
    // add openapi-processor-gradle plugin
    id 'io.openapiprocessor.openapi-processor' version '<version>'
}
----

== configuring processor-spring

The plugin will add an `openapiProcessor` configuration block used to configure the processors. Configuration for a specific processor belongs inside it with the processor name as configuration block name.

[source,groovy]
----
openapiProcessor {

    spring {
        processor 'io.openapiprocessor:openapi-processor-spring:<version>'
        apiPath "$projectDir/src/api/openapi.yaml"
        targetDir "$projectDir/build/openapi"
        mapping "$projectDir/mapping.yaml"
        parser "INTERNAL"
    }

}
----

* `processor`: (**required**) the processor dependency. This works in the same way as adding a dependency to a configuration in the gradle `dependencies` block. It is given here to avoid unwanted side effects on the build dependencies of the project.

* `apiPath`: (**required**) the path to the `openapi.yaml` file and the main input for the processor. If set in the top-level block, it will be used for all configured processors.

* `targetDir`: (**required**) the output folder for generating interfaces and models. This is the parent of the `packageName` folder tree. It is recommended to set this to a subfolder of gradle's standard `build` directory, so it is cleared by the `clean` task and does not pollute the `sources`
directory.
+
See <<running processor-spring>> how to include the `targetDir` in compilation and packing.

* `mapping`: (**required**) provides the processor mapping options. This is a path to the YAML file. See xref:processor/configuration.adoc[Configuration] for a description of the mapping YAML. This replaces the `typeMappings` option.

* `showWarnings`: (**optional**) `true` to show warnings from the open api parser or `false` (default) to show no warnings (this option has currently no effect).

* `parser`: (**optional**), sets the openapi parser used to read the OpenAPI description. Available values are `SWAGGER`, `OPENAPI4J` or `INTERNAL` (default).
** `INTERNAL`: link:{openapi-parser}[internal OpenAPI parser, window="_blank"], supports *OpenAPI 3.0.x* & *OpenAPI 3.1.0*.
** `SWAGGER`: link:{swagger-parser}[Swagger OpenAPI parser, window="_blank"], supports *OpenAPI 3.0.x*
** `OPENAPI4J`: link:{openapi4j}[openapi4j OpenAPI parser, window="_blank"], supports *OpenAPI 3.0.x*. It provides better validation than `SWAGGER`, unfortunately it is no longer maintained and is deprecated.
*** the parser provides JSON schema validation.

== running processor-spring

The plugin will add a gradle task `processSpring` to run the processor.

To automatically generate & compile the processor output two additional configurations are necessary.

* the `sourceSets` are extended to include the processor output (assuming a java project):
+
[source,groovy]
----
sourceSets {
    main {
        java {
            // add generated files
            srcDir 'build/openapi'
        }
    }
}
----

* and the `compileJava` task gets a dependency on `processSpring`, so it runs before compilation (again, assuming a java project):
+
[source,groovy]
----
// generate api before compiling
compileJava.dependsOn ('processSpring')
----

Adding automatic compilation in this way will also automatically include the generated files into the `jar` build artifact.
